//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 5 storyboards.
  struct storyboard {
    /// Storyboard `AddPlant`.
    static let addPlant = _R.storyboard.addPlant()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    /// Storyboard `MyPlants`.
    static let myPlants = _R.storyboard.myPlants()
    /// Storyboard `MyTasks`.
    static let myTasks = _R.storyboard.myTasks()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "AddPlant", bundle: ...)`
    static func addPlant(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.addPlant)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "MyPlants", bundle: ...)`
    static func myPlants(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.myPlants)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "MyTasks", bundle: ...)`
    static func myTasks(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.myTasks)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 11 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")
    /// Color `Accent`.
    static let accent = Rswift.ColorResource(bundle: R.hostingBundle, name: "Accent")
    /// Color `BackgroundDarker`.
    static let backgroundDarker = Rswift.ColorResource(bundle: R.hostingBundle, name: "BackgroundDarker")
    /// Color `Background`.
    static let background = Rswift.ColorResource(bundle: R.hostingBundle, name: "Background")
    /// Color `DarkSecondAccent`.
    static let darkSecondAccent = Rswift.ColorResource(bundle: R.hostingBundle, name: "DarkSecondAccent")
    /// Color `ImageBack`.
    static let imageBack = Rswift.ColorResource(bundle: R.hostingBundle, name: "ImageBack")
    /// Color `LightAccent`.
    static let lightAccent = Rswift.ColorResource(bundle: R.hostingBundle, name: "LightAccent")
    /// Color `PrimaryText`.
    static let primaryText = Rswift.ColorResource(bundle: R.hostingBundle, name: "PrimaryText")
    /// Color `SecondAccentBackground`.
    static let secondAccentBackground = Rswift.ColorResource(bundle: R.hostingBundle, name: "SecondAccentBackground")
    /// Color `SecondAccent`.
    static let secondAccent = Rswift.ColorResource(bundle: R.hostingBundle, name: "SecondAccent")
    /// Color `SecondaryText`.
    static let secondaryText = Rswift.ColorResource(bundle: R.hostingBundle, name: "SecondaryText")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "Accent", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accent(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accent, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "Background", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.background, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "BackgroundDarker", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func backgroundDarker(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.backgroundDarker, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "DarkSecondAccent", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func darkSecondAccent(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.darkSecondAccent, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "ImageBack", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func imageBack(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.imageBack, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "LightAccent", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func lightAccent(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.lightAccent, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "PrimaryText", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func primaryText(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.primaryText, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "SecondAccent", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func secondAccent(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.secondAccent, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "SecondAccentBackground", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func secondAccentBackground(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.secondAccentBackground, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "SecondaryText", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func secondaryText(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.secondaryText, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "Accent", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accent(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accent.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "Background", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func background(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.background.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "BackgroundDarker", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func backgroundDarker(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.backgroundDarker.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "DarkSecondAccent", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func darkSecondAccent(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.darkSecondAccent.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "ImageBack", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func imageBack(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.imageBack.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "LightAccent", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func lightAccent(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.lightAccent.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "PrimaryText", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func primaryText(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.primaryText.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "SecondAccent", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func secondAccent(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.secondAccent.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "SecondAccentBackground", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func secondAccentBackground(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.secondAccentBackground.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "SecondaryText", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func secondaryText(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.secondaryText.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 38 images.
  struct image {
    /// Image `Add`.
    static let add = Rswift.ImageResource(bundle: R.hostingBundle, name: "Add")
    /// Image `Articles`.
    static let articles = Rswift.ImageResource(bundle: R.hostingBundle, name: "Articles")
    /// Image `Explore`.
    static let explore = Rswift.ImageResource(bundle: R.hostingBundle, name: "Explore")
    /// Image `Image`.
    static let image = Rswift.ImageResource(bundle: R.hostingBundle, name: "Image")
    /// Image `Profile`.
    static let profile = Rswift.ImageResource(bundle: R.hostingBundle, name: "Profile")
    /// Image `back`.
    static let back = Rswift.ImageResource(bundle: R.hostingBundle, name: "back")
    /// Image `bathroom`.
    static let bathroom = Rswift.ImageResource(bundle: R.hostingBundle, name: "bathroom")
    /// Image `bedroom`.
    static let bedroom = Rswift.ImageResource(bundle: R.hostingBundle, name: "bedroom")
    /// Image `check_circle`.
    static let check_circle = Rswift.ImageResource(bundle: R.hostingBundle, name: "check_circle")
    /// Image `default10`.
    static let default10 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default10")
    /// Image `default11`.
    static let default11 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default11")
    /// Image `default12`.
    static let default12 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default12")
    /// Image `default13`.
    static let default13 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default13")
    /// Image `default14`.
    static let default14 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default14")
    /// Image `default15`.
    static let default15 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default15")
    /// Image `default16`.
    static let default16 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default16")
    /// Image `default17`.
    static let default17 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default17")
    /// Image `default18`.
    static let default18 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default18")
    /// Image `default1`.
    static let default1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default1")
    /// Image `default2`.
    static let default2 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default2")
    /// Image `default3`.
    static let default3 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default3")
    /// Image `default4`.
    static let default4 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default4")
    /// Image `default5`.
    static let default5 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default5")
    /// Image `default6`.
    static let default6 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default6")
    /// Image `default7`.
    static let default7 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default7")
    /// Image `default8`.
    static let default8 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default8")
    /// Image `default9`.
    static let default9 = Rswift.ImageResource(bundle: R.hostingBundle, name: "default9")
    /// Image `drop`.
    static let drop = Rswift.ImageResource(bundle: R.hostingBundle, name: "drop")
    /// Image `emptyState`.
    static let emptyState = Rswift.ImageResource(bundle: R.hostingBundle, name: "emptyState")
    /// Image `kitchen`.
    static let kitchen = Rswift.ImageResource(bundle: R.hostingBundle, name: "kitchen")
    /// Image `livingroom`.
    static let livingroom = Rswift.ImageResource(bundle: R.hostingBundle, name: "livingroom")
    /// Image `office`.
    static let office = Rswift.ImageResource(bundle: R.hostingBundle, name: "office")
    /// Image `plantPlaceholder`.
    static let plantPlaceholder = Rswift.ImageResource(bundle: R.hostingBundle, name: "plantPlaceholder")
    /// Image `planticon1`.
    static let planticon1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "planticon1")
    /// Image `terrace`.
    static let terrace = Rswift.ImageResource(bundle: R.hostingBundle, name: "terrace")
    /// Image `watercolor1`.
    static let watercolor1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "watercolor1")
    /// Image `watercolor2`.
    static let watercolor2 = Rswift.ImageResource(bundle: R.hostingBundle, name: "watercolor2")
    /// Image `watercolor3`.
    static let watercolor3 = Rswift.ImageResource(bundle: R.hostingBundle, name: "watercolor3")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Add", bundle: ..., traitCollection: ...)`
    static func add(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.add, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Articles", bundle: ..., traitCollection: ...)`
    static func articles(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.articles, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Explore", bundle: ..., traitCollection: ...)`
    static func explore(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.explore, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Image", bundle: ..., traitCollection: ...)`
    static func image(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.image, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "Profile", bundle: ..., traitCollection: ...)`
    static func profile(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.profile, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "back", bundle: ..., traitCollection: ...)`
    static func back(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.back, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "bathroom", bundle: ..., traitCollection: ...)`
    static func bathroom(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bathroom, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "bedroom", bundle: ..., traitCollection: ...)`
    static func bedroom(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bedroom, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "check_circle", bundle: ..., traitCollection: ...)`
    static func check_circle(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.check_circle, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default1", bundle: ..., traitCollection: ...)`
    static func default1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default1, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default10", bundle: ..., traitCollection: ...)`
    static func default10(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default10, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default11", bundle: ..., traitCollection: ...)`
    static func default11(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default11, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default12", bundle: ..., traitCollection: ...)`
    static func default12(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default12, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default13", bundle: ..., traitCollection: ...)`
    static func default13(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default13, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default14", bundle: ..., traitCollection: ...)`
    static func default14(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default14, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default15", bundle: ..., traitCollection: ...)`
    static func default15(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default15, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default16", bundle: ..., traitCollection: ...)`
    static func default16(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default16, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default17", bundle: ..., traitCollection: ...)`
    static func default17(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default17, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default18", bundle: ..., traitCollection: ...)`
    static func default18(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default18, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default2", bundle: ..., traitCollection: ...)`
    static func default2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default2, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default3", bundle: ..., traitCollection: ...)`
    static func default3(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default3, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default4", bundle: ..., traitCollection: ...)`
    static func default4(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default4, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default5", bundle: ..., traitCollection: ...)`
    static func default5(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default5, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default6", bundle: ..., traitCollection: ...)`
    static func default6(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default6, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default7", bundle: ..., traitCollection: ...)`
    static func default7(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default7, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default8", bundle: ..., traitCollection: ...)`
    static func default8(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default8, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "default9", bundle: ..., traitCollection: ...)`
    static func default9(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.default9, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "drop", bundle: ..., traitCollection: ...)`
    static func drop(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.drop, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "emptyState", bundle: ..., traitCollection: ...)`
    static func emptyState(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.emptyState, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "kitchen", bundle: ..., traitCollection: ...)`
    static func kitchen(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.kitchen, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "livingroom", bundle: ..., traitCollection: ...)`
    static func livingroom(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.livingroom, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "office", bundle: ..., traitCollection: ...)`
    static func office(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.office, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "plantPlaceholder", bundle: ..., traitCollection: ...)`
    static func plantPlaceholder(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.plantPlaceholder, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "planticon1", bundle: ..., traitCollection: ...)`
    static func planticon1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.planticon1, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "terrace", bundle: ..., traitCollection: ...)`
    static func terrace(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.terrace, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "watercolor1", bundle: ..., traitCollection: ...)`
    static func watercolor1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.watercolor1, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "watercolor2", bundle: ..., traitCollection: ...)`
    static func watercolor2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.watercolor2, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "watercolor3", bundle: ..., traitCollection: ...)`
    static func watercolor3(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.watercolor3, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.nib` struct is generated, and contains static references to 6 nibs.
  struct nib {
    /// Nib `HeaderView`.
    static let headerView = _R.nib._HeaderView()
    /// Nib `PickRoomCell`.
    static let pickRoomCell = _R.nib._PickRoomCell()
    /// Nib `PlantCell`.
    static let plantCell = _R.nib._PlantCell()
    /// Nib `PlantInfoView`.
    static let plantInfoView = _R.nib._PlantInfoView()
    /// Nib `TaskCell`.
    static let taskCell = _R.nib._TaskCell()
    /// Nib `WateringCell`.
    static let wateringCell = _R.nib._WateringCell()

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "HeaderView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.headerView) instead")
    static func headerView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.headerView)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "PickRoomCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.pickRoomCell) instead")
    static func pickRoomCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.pickRoomCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "PlantCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.plantCell) instead")
    static func plantCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.plantCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "PlantInfoView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.plantInfoView) instead")
    static func plantInfoView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.plantInfoView)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "TaskCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.taskCell) instead")
    static func taskCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.taskCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "WateringCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.wateringCell) instead")
    static func wateringCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.wateringCell)
    }
    #endif

    static func headerView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> HeaderView? {
      return R.nib.headerView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? HeaderView
    }

    static func pickRoomCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> PickRoomCell? {
      return R.nib.pickRoomCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? PickRoomCell
    }

    static func plantCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> PlantCell? {
      return R.nib.plantCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? PlantCell
    }

    static func plantInfoView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.plantInfoView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    static func taskCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TaskCell? {
      return R.nib.taskCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TaskCell
    }

    static func wateringCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> WateringCell? {
      return R.nib.wateringCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? WateringCell
    }

    fileprivate init() {}
  }

  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `defaultPlantImageCell`.
    static let defaultPlantImageCell: Rswift.ReuseIdentifier<DefaultPlantImageCell> = Rswift.ReuseIdentifier(identifier: "defaultPlantImageCell")

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try nib.validate()
    #endif
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _PickRoomCell.validate()
      try _PlantCell.validate()
      try _PlantInfoView.validate()
    }

    struct _HeaderView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "HeaderView"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> HeaderView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? HeaderView
      }

      fileprivate init() {}
    }

    struct _PickRoomCell: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "PickRoomCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> PickRoomCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? PickRoomCell
      }

      static func validate() throws {
        if UIKit.UIImage(named: "kitchen", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'kitchen' is used in nib 'PickRoomCell', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
          if UIKit.UIColor(named: "DarkSecondAccent", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'DarkSecondAccent' is used in nib 'PickRoomCell', but couldn't be loaded.") }
        }
      }

      fileprivate init() {}
    }

    struct _PlantCell: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "PlantCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> PlantCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? PlantCell
      }

      static func validate() throws {
        if UIKit.UIImage(named: "plantPlaceholder", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'plantPlaceholder' is used in nib 'PlantCell', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }

    struct _PlantInfoView: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "PlantInfoView"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      static func validate() throws {
        if UIKit.UIImage(named: "check_circle", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'check_circle' is used in nib 'PlantInfoView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "drop", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'drop' is used in nib 'PlantInfoView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "plantPlaceholder", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'plantPlaceholder' is used in nib 'PlantInfoView', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
          if UIKit.UIColor(named: "Accent", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'Accent' is used in nib 'PlantInfoView', but couldn't be loaded.") }
          if UIKit.UIColor(named: "DarkSecondAccent", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'DarkSecondAccent' is used in nib 'PlantInfoView', but couldn't be loaded.") }
          if UIKit.UIColor(named: "LightAccent", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'LightAccent' is used in nib 'PlantInfoView', but couldn't be loaded.") }
          if UIKit.UIColor(named: "PrimaryText", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'PrimaryText' is used in nib 'PlantInfoView', but couldn't be loaded.") }
          if UIKit.UIColor(named: "SecondaryText", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'SecondaryText' is used in nib 'PlantInfoView', but couldn't be loaded.") }
        }
      }

      fileprivate init() {}
    }

    struct _TaskCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "TaskCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> TaskCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TaskCell
      }

      fileprivate init() {}
    }

    struct _WateringCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "WateringCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> WateringCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? WateringCell
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try addPlant.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try main.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try myPlants.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try myTasks.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct addPlant: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = PickRoomController

      let addPlantPictureController = StoryboardViewControllerResource<AddPlantPictureController>(identifier: "AddPlantPictureController")
      let bundle = R.hostingBundle
      let choosePlantTitleController = StoryboardViewControllerResource<ChoosePlantTitleController>(identifier: "ChoosePlantTitleController")
      let defaultPlantPicturesController = StoryboardViewControllerResource<DefaultPlantPicturesController>(identifier: "DefaultPlantPicturesController")
      let name = "AddPlant"
      let pickRoomController = StoryboardViewControllerResource<PickRoomController>(identifier: "PickRoomController")
      let setWateringCycleController = StoryboardViewControllerResource<SetWateringCycleController>(identifier: "SetWateringCycleController")

      func addPlantPictureController(_: Void = ()) -> AddPlantPictureController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: addPlantPictureController)
      }

      func choosePlantTitleController(_: Void = ()) -> ChoosePlantTitleController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: choosePlantTitleController)
      }

      func defaultPlantPicturesController(_: Void = ()) -> DefaultPlantPicturesController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: defaultPlantPicturesController)
      }

      func pickRoomController(_: Void = ()) -> PickRoomController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: pickRoomController)
      }

      func setWateringCycleController(_: Void = ()) -> SetWateringCycleController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: setWateringCycleController)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "default1", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'default1' is used in storyboard 'AddPlant', but couldn't be loaded.") }
        if UIKit.UIImage(named: "planticon1", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'planticon1' is used in storyboard 'AddPlant', but couldn't be loaded.") }
        if UIKit.UIImage(named: "watercolor2", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'watercolor2' is used in storyboard 'AddPlant', but couldn't be loaded.") }
        if UIKit.UIImage(named: "watercolor3", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'watercolor3' is used in storyboard 'AddPlant', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
          if UIKit.UIColor(named: "Accent", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'Accent' is used in storyboard 'AddPlant', but couldn't be loaded.") }
          if UIKit.UIColor(named: "BackgroundDarker", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'BackgroundDarker' is used in storyboard 'AddPlant', but couldn't be loaded.") }
          if UIKit.UIColor(named: "DarkSecondAccent", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'DarkSecondAccent' is used in storyboard 'AddPlant', but couldn't be loaded.") }
          if UIKit.UIColor(named: "LightAccent", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'LightAccent' is used in storyboard 'AddPlant', but couldn't be loaded.") }
          if UIKit.UIColor(named: "SecondAccent", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'SecondAccent' is used in storyboard 'AddPlant', but couldn't be loaded.") }
        }
        if _R.storyboard.addPlant().addPlantPictureController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'addPlantPictureController' could not be loaded from storyboard 'AddPlant' as 'AddPlantPictureController'.") }
        if _R.storyboard.addPlant().choosePlantTitleController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'choosePlantTitleController' could not be loaded from storyboard 'AddPlant' as 'ChoosePlantTitleController'.") }
        if _R.storyboard.addPlant().defaultPlantPicturesController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'defaultPlantPicturesController' could not be loaded from storyboard 'AddPlant' as 'DefaultPlantPicturesController'.") }
        if _R.storyboard.addPlant().pickRoomController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'pickRoomController' could not be loaded from storyboard 'AddPlant' as 'PickRoomController'.") }
        if _R.storyboard.addPlant().setWateringCycleController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'setWateringCycleController' could not be loaded from storyboard 'AddPlant' as 'SetWateringCycleController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "Main"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct myPlants: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let myPlantsController = StoryboardViewControllerResource<MyPlantsController>(identifier: "MyPlantsController")
      let name = "MyPlants"
      let plantInfoController = StoryboardViewControllerResource<PlantInfoController>(identifier: "PlantInfoController")

      func myPlantsController(_: Void = ()) -> MyPlantsController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: myPlantsController)
      }

      func plantInfoController(_: Void = ()) -> PlantInfoController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: plantInfoController)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "Add", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Add' is used in storyboard 'MyPlants', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Explore", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Explore' is used in storyboard 'MyPlants', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.myPlants().myPlantsController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'myPlantsController' could not be loaded from storyboard 'MyPlants' as 'MyPlantsController'.") }
        if _R.storyboard.myPlants().plantInfoController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'plantInfoController' could not be loaded from storyboard 'MyPlants' as 'PlantInfoController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct myTasks: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = MyTasksController

      let bundle = R.hostingBundle
      let myTasksController = StoryboardViewControllerResource<MyTasksController>(identifier: "MyTasksController")
      let name = "MyTasks"

      func myTasksController(_: Void = ()) -> MyTasksController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: myTasksController)
      }

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.myTasks().myTasksController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'myTasksController' could not be loaded from storyboard 'MyTasks' as 'MyTasksController'.") }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
